main_source/templates/accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('register/',views.registerPage,name="register"),
    path('shopregister/',views.shopOwnerRegisterPage,name="shopregister"),
    path('token/',views.token_send,name="token_send"),
    path('success/',views.success,name="success"),
    path('verify/<auth_token>',views.verify,name="verify"),
    path('error/',views.error_page,name='error'),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('user/dashboard/',views.userPage,name='user-page'),
    path('account/',views.viewAccount,name='account'),
    path('account/edit/',views.accountSettings,name='edit_account'),
    path('change-password/',views.change_password,name = 'change_password'),
    path('', views.home,name='home'),
    path('products/', views.products,name='products'),
    path('flash_sell/', views.flashSell,name='flash'),
    path('products/setting/<str:pk>/', views.productSetting, name='product_setting'),
    path('customer/<str:pk>/', views.customers,name='customer'),
    path('update_order/<str:pk>/',views.updateOrder,name='update_order'),
    path('update_stock/<str:pk>/',views.updateStock,name='update_stock'),
    path('delete_order/<str:pk>/',views.deleteOrder,name='delete_order'),
    path('mail/',views.mail_letter,name='mail'),
    path('create/tag/',views.createTag,name='tag'),
    path('create/category/',views.createCategory,name='category'),
    path('reset-password/', PasswordResetView.as_view(
        template_name= 'accounts/reset_password.html',
        success_url=reverse_lazy('password_reset_done'),
        email_template_name= 'accounts/reset_password_email.html'
    ), name='reset_password'),

    path('reset-password/done/',PasswordResetDoneView.as_view(
        template_name= 'accounts/reset_password_done.html'
    ),name= 'password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(
        template_name= 'accounts/reset_password_confirm.html',
         success_url=reverse_lazy('password_reset_complete'),
    ),name= 'password_reset_confirm' ),
    path('reset-password/complete/',PasswordResetCompleteView.as_view(
        template_name= 'accounts/reset_password_complete.html'
    ),name ='password_reset_complete')
]

main_source/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.home,name="home"),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('register/',views.registerPage,name="register"),
    path('token/',views.token_send,name="token_send"),
    path('success/',views.success,name="success"),
    path('verify/<auth_token>',views.verify,name="verify"),
    path('error/',views.error_page,name='error'),
    path('join/mess/',views.joinMess,name='join_mess'),
    path('create/mess/',views.createMess,name='create_mess'),
]

mealmanager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main_source.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main_source/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Mess(models.Model):
    name = models.CharField(max_length=100,blank = True, null=True)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name

class Member(models.Model):
    mess = models.ForeignKey(Mess, null = True,blank=True ,on_delete=models.CASCADE)
    user = models.OneToOneField(User, null = True,blank=True ,on_delete=models.CASCADE)
    phone = models.DecimalField(decimal_places=15,max_digits=15,blank=True,null=True)
    profile_pic = models.ImageField(default="profile.png",null = True,blank = True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

class Meals(models.Model):
    user = models.OneToOneField(User, null = True,blank=True ,on_delete=models.CASCADE)
    todays_meal = models.IntegerField(default=0,blank=True,null=True)
    total_meal = models.IntegerField(default=0,blank=True,null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

class AmountSpend(models.Model):
    mess = models.ForeignKey(Mess, null = True,blank=True ,on_delete=models.CASCADE)
    user = models.OneToOneField(User, null = True,blank=True ,on_delete=models.CASCADE)
    spend_on = models.CharField(max_length= 250,blank=True,null=True)
    amount = models.IntegerField(default=0,blank=True,null=True)
    person_spend = models.FloatField(default=0,blank=True,null=True)
    spend_total = models.FloatField(default=0,blank=True,null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

class Bills(models.Model):
    mess = models.ForeignKey(Mess, null = True,blank=True ,on_delete=models.CASCADE)
    bill_on = models.CharField(max_length= 250,blank=True,null=True)
    amount = models.IntegerField(default=0,blank=True,null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.mess)

class CashDeposit(models.Model):
    mess = models.ForeignKey(Mess, null = True,blank=True ,on_delete=models.CASCADE)
    user = models.OneToOneField(User, null = True,blank=True ,on_delete=models.CASCADE)
    deposit_for = models.CharField(max_length= 250,blank=True,null=True)
    amount = models.IntegerField(default=0,blank=True,null=True)
    balance = models.FloatField(default=0,blank=True,null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=100)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

def create_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user = instance)
        print('Profile created')


def update_profile(sender, instance, created, **kwargs):
    if created == False:
        instance.UserProfile.save()
        print('Profile Updated')

main_source/forms.py
from django.forms import ModelForm, fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UpdateProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields =['email','first_name','last_name','password']

class CreateMessForm(ModelForm):

    class Meta:
        model = Mess
        fields = "name",

class AddMealForm(ModelForm):

    class Meta:
        model = Meals
        fields = "todays_meal",

class AmountSpendForm(ModelForm):
    
    class Meta:
        model = AmountSpend
        fields = ['spend_on','amount']

class BillsForm(ModelForm):

    class Meta:
        model = Bills
        fields = ['bill_on','amount']

class CashDepositForm(ModelForm):

    class Meta:
        model = CashDeposit
        fields = ['deposit_for','amount']

main_source/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.models import User
import uuid
from .forms import *
from .models import *
import datetime
from datetime import date
from datetime import timedelta
from django.conf import settings
from django.core.mail import send_mail
from django_pandas.io import read_frame
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticted_user, allowed_users

# Create your views here.
@login_required(login_url='login')
def home(request):
    now = datetime.datetime.now()
    year = date.today().year
    month = date.today().month
    member = request.user.member
    if request.user.groups.filter(name = 'member').exists() or request.user.groups.filter(name = 'manager').exists():
        form1 = AddMealForm()
        form2 = AmountSpendForm()
        form3 = BillsForm()
        form4 = CashDepositForm()
        mess_id = member.mess.id
        mess = Mess.objects.get(id=mess_id)
        users = mess.members.all()
        total_user = users.count()
        total_meals = 0
        for l in users:
            total_meals += l.meals.total_meal
        spend = AmountSpend.objects.filter(mess=mess,date_created__month__gte=month)
        bill = Bills.objects.filter(mess=mess)
        cashdeposit = CashDeposit.objects.filter(mess=mess,date_created__month__gte=month)
        total_deposit = 0
        for k in cashdeposit:
            total_deposit += k.amount
        total_bill = 0
        for j in bill:
            total_bill += j.amount
        total_spend = 0
        for i in spend:
            total_spend += i.amount
        if total_spend > 0:
            meal_rate = 0
            meal_rate = float(total_spend/total_meals)
        else:
            meal_rate = 0
        for m in users:
            person_spend = 0
            person_spend += float(m.meals.total_meal*meal_rate)
            m.amountspend.spend_total = float(person_spend+(total_bill/total_user))
            m.amountspend.person_spend = person_spend
            m.cashdeposit.balance = float(m.cashdeposit.amount-m.amountspend.spend_total)
            m.amountspend.save()
            m.cashdeposit.save()
        main_balance = 0
        main_balance = total_deposit - (total_bill+total_spend)
        
        
        if request.method == 'POST' and 'todays_meal' in request.POST:
            form1 = AddMealForm(request.POST)
            
            if form1.is_valid():
                user_id = request.POST.get('user_id')
                todays_meal = request.POST.get('todays_meal')
                meal = Meals.objects.get(user_id=user_id)
                meal.todays_meal = todays_meal
                total = meal.total_meal
                total += int(todays_meal)
                meal.total_meal = total
                meal.save()
                return redirect('/')
        else:
            form1 = AddMealForm(request.POST)

        if request.method == 'POST' and 'spend_on' in request.POST:
            form2 = AmountSpendForm(request.POST)

            if form2.is_valid():
                user_id = request.POST.get('user_id')
                amount = request.POST.get('amount')
                spend_on = request.POST.get('spend_on')
                user = User.objects.get(id=user_id)
                amountspend = AmountSpend.objects.get(mess=mess,user_id=user_id)
                spend_amount = amountspend.amount
                spend_amount += int(amount)
                amountspend.amount = spend_amount
                amountspend.spend_on = spend_on
                amountspend.save()
                return redirect('/')
        else:
            form2 = AmountSpendForm(request.POST)
        
        if request.method == 'POST' and 'bill_on' in request.POST:
            form3 = BillsForm(request.POST)

            if form3.is_valid():
                bill_on = request.POST.get('bill_on')
                amount = request.POST.get('amount')
                bills = Bills.objects.create(mess=mess)
                bills.bill_on = bill_on
                bills.amount = amount
                bills.save()
                return redirect('/')
        else:
            form3 = BillsForm(request.POST)
        
        if request.method == 'POST' and 'deposit_for' in request.POST:
            form4 = CashDepositForm(request.POST)

            if form4.is_valid():
                user_id = request.POST.get('user_id')
                amount = request.POST.get('amount')
                deposit_for = request.POST.get('deposit_for')
                cashdeposit = CashDeposit.objects.get(mess=mess,user_id=user_id)
                deposit_amount = cashdeposit.amount
                deposit_amount += int(amount)
                cashdeposit.amount = deposit_amount
                cashdeposit.deposit_for = deposit_for
                cashdeposit.save()
                return redirect('/')
        else:
            form4 = CashDepositForm(request.POST)

        context ={
        'now':now,
        'member':member,
        'total_meals':total_meals,
        'form1':form1,
        'form2':form2,
        'form3':form3,
        'form4':form4,
        'main_balance':main_balance,
        'meal_rate':meal_rate,
        'total_deposit':total_deposit,
        'bill':bill,
        'total_bill':total_bill,
        'total_spend':total_spend,
        'mess':mess,
    }
        return render(request,'section/home.html',context)

    else:
        context = {'now':now,
        'member':member}

    return render(request,'section/home.html',context)

@unauthenticted_user
def registerPage(request):
    form = CreateUserForm()
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password1')
    role = request.POST.get('role')
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        try:
            if User.objects.filter(username=username).first():
                messages.success(request, 'Username is taken.')
                return redirect('/register')

            elif User.objects.filter(email=email).first():
                messages.success(request, 'This Email is taken.')
                return redirect('/register')

            if form.is_valid():
                user_obj = User.objects.create(username =username,email=email)
                user_obj.set_password(password)
                user_obj.save()
                auth_token=str(uuid.uuid4())
                profile_obj = UserProfile.objects.create(user = user_obj,auth_token=auth_token)
                profile_obj.save()
                meal = Meals.objects.create(user=user_obj)
                meal.save()
                if role == "member":
                    group = Group.objects.get(name = 'member')
                    user_obj.groups.add(group)
                elif role == "manager":
                    group = Group.objects.get(name = 'manager')
                    user_obj.groups.add(group)
                Member.objects.create(
                    user = user_obj
                )
                send_mail_after_registration(email,auth_token)
                messages.success(request,'Account was created for ' + username)
                return redirect('/token')
        
        except Exception as e:
            print(e)

    context = {'form':form}
    return render(request,'accounts/signup.html',context)

def success(request):
    return render(request, 'accounts/success.html')

def token_send(request):
    return render(request, 'accounts/token_send.html')

def send_mail_after_registration(email,token):
    subject = 'Account activation for Meal Manager...'
    message = f'Hello there! Click this link to verify your account http://127.0.0.1:8000/verify/{token}'
    email_form = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject,message,email_form,recipient_list)

def verify(request,auth_token):
    try:
        profile_obj = UserProfile.objects.filter(auth_token = auth_token).first()
        if profile_obj:
            profile_obj.is_verified = True
            profile_obj.save()
            messages.success(request,'Your account has been verified')
            return redirect('/login')
        else:
            return redirect('/error')
    
    except Exception as e:
        print(e)

def error_page(request):
    return render(request,'accounts/error.html')

@unauthenticted_user
def loginPage(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username=username, password=password)

        if user is not None:
            login(request,user)
            if user.member.mess is not None:
                return redirect('home')
            else:
                if request.user.groups.filter(name = 'member').exists():
                    return redirect('join_mess')
                else: 
                    return redirect('create_mess')

        else:
            messages.info(request,'Username or Password is incorrect')
    context = {}
    return render(request,'accounts/login.html',context)

def logoutUser(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
def joinMess(request):
    mess = Mess.objects.all()
    if request.method == "POST":
        user_id = request.POST.get('user_id')
        mess_id = request.POST.get('mess_id')
        mess = Mess.objects.get(id=mess_id)
        user = User.objects.get(id=user_id)
        amountspend = AmountSpend.objects.create(mess=mess,user=user)
        amountspend.save()
        cashdeposit = CashDeposit.objects.create(mess=mess,user=user)
        cashdeposit.save()
        member = Member.objects.get(user=user)
        member.mess = mess
        member.save()

main_source/templates/section/addbills.html
<section id="addbills">
    <div class="container">
        <div class="row">
            <div class="col-md-4 heading">
                <h2> Add Bills Section </h2>
                <div class="row">
                    <div class="col-md-6 left_bill">
                        <p>Here you will see the bills for yours mess with 
                            amounts. 
                            You can also see the added date of bills.<br> 
                            <strong>Bills can only added by manager.</strong>  <br><br>
                            <strong>{{mess.name}},</strong><br>
                            <strong>Total Bill : {{total_bill}}</strong> <br>
                        </p>
                    </div>
                    <div class="col-md-6">
                <form method="POST">
                    {% csrf_token %}
                    <label for="id_bill_on">Bill Name</label>
                    <input type="text" name="bill_on" maxlength="250" id="id_bill_on">
                    <label for="id_amount">Amount</label>
                    <input type="number" name="amount" id="id_amount">
                    <input type="submit" id="submit" value="Add Bill">
                </form>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-body">
                    <table class="table table-dark">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Bills On</th>
                                <th scope="col">Bill Amount</th>
                                <th scope="col">Bill Added On</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in bill %}
                            <tr>
                                <td>{{i.bill_on}}</td>
                                <td>{{i.amount}}</td>
                                <td>{{i.date_created }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<style>
#addbills{
    width: 100%;
    background: var(--white);
    margin: 20px;
}
#addbills .col-md-8{
    padding: 0 40px;
}
#addbills .table tbody{
    max-height: 600px !important;
    overflow: scroll !important;
}
.heading{
    color: var(--black);
    background-color: var(--white);
    border-color: var(--white);
    border-radius: 15px;
}
.heading h2{
    color: var(--white);
    background-color: var(--black);
    border-color: var(--black);
    width: 100%;
    border-top-left-radius: 15px;
    border-top-right-radius: 15px;
    text-align: center;
    text-transform: uppercase;
}
.left_bill{
    border-right: 1px solid var(--black)
}
.table .thead-dark th {
    color: var(--white);
    background-color: var(--black);
    border-color: var(--black);
    text-transform: uppercase;
}

input[type=color], input[type=date], input[type=datetime-local], input[type=datetime], input[type=email], input[type=month], input[type=number], input[type=password], input[type=search], input[type=tel], input[type=text], input[type=time], input[type=url], input[type=week], textarea {
  background-color: transparent;
  background-image: linear-gradient(to right,#ff005e 0,#ff7101 70%);
  background-repeat: no-repeat;
  background-position: 0 calc(100% + 3px),0 0;
  background-size: 100% 3px;
  box-shadow: none;
  border: 0;
  border-bottom: 3px solid #ff005e;
  color: #000;
  font-weight: 400;
  -webkit-font-smoothing: antialiased;
  font-size: 20px;
  line-height: 1.5;
  outline: 0 none;
  padding: .25rem 0;
  transition: border-color .2s linear;
  width: 100%;
  
}
#submit {
    color: var(--white);
    margin-top: 40px;
    transition: color 300ms;
    background-image: linear-gradient(to right,#ff005e 0,#ff7101 70%);
    border-radius: 45px;
    width: 50%;
}
</style>

main_source/templates/section/amountspend.html
{% load static %}
<section class="pt-5 pb-5" id="meals">
    <div class="container-fluid">
      <div class="row">
          <div class="col-1">
          </div>
          <div class="col-5">
            <h3 class="mb-3">Spend Section </h3>
        </div>
          <div class="col-6 text-right">
              
          <a class="btn btn-outline-secondary mx-1 prev" onclick="prev()" href="javascript:void(0)" title="Previous">
            <i class="fa fa-lg fa-chevron-left"></i>
          </a>
          <a class="btn btn-outline-secondary mx-1 next" onclick="next()" href="javascript:void(0)" title="Next">
            <i class="fa fa-lg fa-chevron-right"></i>
          </a>
          </div>
          <div class="col-4 left_meal">
            <div class="meal_content">
                <p> Here you can see the last added mills and total meal of yours.
                    Also you can see the total spends by meals.
                    <br><br><strong>{{mess.name}},</strong> <br>
                    Total Spend : <strong>{{total_spend |floatformat:2}} Tk</strong> <br>
                </p>
            </div>
              <div class="loader">
                  <div class="rocket">
                    <i class="fa fa-rocket"></i>
                    <i class="fa fa-cloud" style="--i:0;"></i>
                    <i class="fa fa-cloud" style="--i:1;"></i>
                    <i class="fa fa-cloud" style="--i:2;"></i>
                    <i class="fa fa-cloud" style="--i:3;"></i>
                  </div>
                  <span><i></i></span>
              </div>
          </div>
          <div class="col-8">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner row w-100 mx-auto" id="activ-2">
                {% for member in mess.members.all %}
                <div class="carousel-item col-md-4" >
                <div class="card">
                  <div class="icon"><img src="{{ member.member.profile_pic.url }}" alt=""></div>
                  <div class="content">
                      <h2>{{member.username}}</h2>
                      <form method="POST">
                          {% csrf_token %}
                          <input type="hidden" name = "user_id" value="{{member.id}}">
                          <input type="text" placeholder="Spends on...." name="spend_on" maxlength="250" id="id_spend_on">
                          <input type="number" placeholder="Enter Amount..." name="amount" id="id_amount">
                          <button type="submit" class="btn btn-danger">Add Spend</button>
                      </form>
                      <p>Spends : {{ member.amountspend.amount|floatformat:2 }}</p>
                  </div>

                </div>
                </div>
                {% endfor %}
                </div>
                </div>
          </div>
      </div>
  </div>
  </section>
<style>
/*-- Meals Section --*/
#meals{
    width: 100%;
    background: var(--white);
}
#meals input{
    background-color: #acacac3b;
    color: #ffffffa8;
    margin-bottom: 10px;
}
#meals .left_meal{
    display: flex;
    justify-content: center;
    align-items: center;
}
#meals .loader{
    position: relative;
    display: flex;
}
#meals .left_meal .meal_content{
    padding: 0 40px;
    display: block;
}
#meals .loader span{
    position: relative;
    width: 250px;
    height: 250px;
    background: var(--white);
    border: 6px solid var(--white);
    border-radius: 50%;
    box-shadow: -8px -8px 15px rgba(255,255,255,1),
    8px 8px 25px rgba(0,0,0,0.15);
    overflow: hidden;
}
#meals .loader span::before{
    content: '';
    position: absolute;
    inset: 0;
    border-radius: 50%;
    box-shadow: inset 10px 10px 20px rgba(0,0,0,0.5),
    inset -5px -5px 15px rgba(255,255,255,1);
}
#meals .loader span::after{
    content: '';
    position: absolute;
    inset: 40px;
    background: var(--white);
    border: 3px solid var(--white);
    border-radius: 50%;
    box-shadow: -8px -8px 25px rgba(255,255,255,1),
    8px 8px 25px rgba(0,0,0,0.25),
    inset 3px 3px 10px rgba(0,0,0,0.15),
    inset -1px -1px 15px rgba(255,255,255,1);
}
#meals .loader span i{
    position: absolute;
    inset: 0;
    border-radius: 50%;
    filter: blur(5px);
    background: linear-gradient(#42abff,#ff4f8b,#ffeb3b);
    animation: animate 1s linear infinite;
}
@keyframes animate{
    0%{
        transform: rotate(0deg);
    }
    100%{
        transform: rotate(360deg);
    }
}
.rocket{
    position: absolute;
    inset: 50px;
    display: flex;
    z-index: 10;
    border-radius: 50%;
    justify-content: center;
    align-items: center;
    overflow: hidden;
}
.rocket .fa-rocket{
    position: absolute;
    color: #ff518c;
    font-size: 3.5em;
    -webkit-text-stroke: 2px #000;
    animation:  animateRocket 0.2s linear infinite;
}
@keyframes animateRocket{
    0%,100%{
        transform: translate(0px,0px) rotate(-45deg);
    }
    50%{
        transform: translate(0px,3px) rotate(-45deg);
    }
}
.fa-cloud{
    position: absolute;
    top: calc(35px * var(--i));
    left: calc(45px * var(--i));
    font-size: 2em;
    color: #fff;
    -webkit-text-stroke: 2px #000;
    animation:  animateClouds 1s linear infinite;
    animation-delay: calc(-0.5s * var(--i));
}
@keyframes animateClouds{
    0%{
        transform: translateY(calc(-35 * 5px));
    }
    100%{
        transform: translateY(calc(35 * 5px));
    }
}
#meals .mb-3{
    color: var(--black);
}
#meals .card{
    position: relative;
    width: 320px;
    height: 450px;
    margin: 30px;
    background: transparent;
    border-radius: 20px;
    border-bottom-left-radius: 160px;
    border-bottom-right-radius: 160px;
    box-shadow: 0 15px 0 #fff,
    inset 0 -15px 0 rgba(255, 255, 255,0.25),
    0 45px 0 rgba(0,0,0,0.15);
    overflow: hidden;
    display: flex;
    float: left;
    justify-content: center;
    align-items: flex-start;
    flex-direction: row;
}
#meals .card::before{
    content: '';
    position: absolute;
    top: -140px;
    left: -40%;
    width: 100%;
    height: 120%;
    background: linear-gradient(90deg,transparent,rgba(255,255,255,0.2));
    transform: rotate(35deg);
    pointer-events: none;
    filter: blur(5px);
}
#meals .card:nth-child(1){
    background: linear-gradient(to bottom,#ff2ae0,#645bf6);
    border: none;
}
#meals .card:nth-child(2){
    background: linear-gradient(to bottom,#ffec61,#f321d7);
    border: none;
}
#meals .card:nth-child(3){
    background: linear-gradient(to bottom,#24ff72,#9a4eff);
    border: none;
}
#meals .card .btn{
    margin: 10px;
}
#meals .icon{
    position: relative;
    width: 140px;
    height: 120px;
    background: var(--white);
    border-bottom-left-radius: 100px;
    border-bottom-right-radius: 100px;
    box-shadow: 0 10px 0 rgba(0,0,0,0.1),
    inset 0 -8px 0 #fff;
    z-index: 1000;
    display: flex;
    justify-content: center;

}
#meals .icon::before{

    content: '';
    position: absolute;
    top: 0;
    left: -50px;
    width: 50px;
    height: 50px;
    background: transparent;
    border-top-right-radius: 50px;
    box-shadow: 15px -15px 0 15px var(--white);
}
#meals .icon::after{

    content: '';
    position: absolute;
    top: 0;
    right: -50px;
    width: 50px;
    height: 50px;
    background: transparent;
    border-top-left-radius: 50px;
    box-shadow: -15px -15px 0 15px var(--white);
}

#meals .icon img{
    color: #fff;
    position: relative;
    height: 100px;
    border-radius: 50%;
    z-index: 10000;
}
#meals .content{
    position: absolute;
    width: 100%;
    padding: 30px;
    padding-top: 140px;
    text-align: center;
}
#meals .content h2{
    font-size: 1.75em;
    color: #fff;
    margin-bottom: 10px;
}
#meals .content p{
    color: #fff;
    line-height: 1.5em;
}
</style>

main_source/templates/section/home.html
{% extends 'main.html' %}
{% load static %}
{% block head %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

{% endblock %}

{% block menu %}

<div class="btns menuToggle">
    <ion-icon name="menu-outline"></ion-icon>
    <ion-icon name="close-outline"></ion-icon>
</div>

{% endblock %}

{% block main %}

<h2>{{mess.name}}</h2>

<p class="copyrightText">{{now}}</p>

<ul class="sci">
    <li><a href=""><ion-icon name="person-circle-outline"></ion-icon></a></li>
    <li><a href=""><ion-icon name="accessibility-outline"></ion-icon></a></li>
    <li><a href="{% url 'logout' %}"><ion-icon name="log-out-outline"></ion-icon></a></li>
</ul>

{% endblock %}

{% block body %}

{% include 'section/meals.html' %}
{% include 'section/addbills.html' %}
{% include 'section/amountspend.html' %}
{% include 'section/cashdeposit.html' %}
{% include 'section/balance.html' %}
<!-- Sidebar Navigation --->
<ul class="navigation">
    <li><a href="">Home</a></li>
    <li><a href="">About</a></li>
    <li><a href="">Package</a></li>
    <li><a href="">Contact</a></li>
</ul>

{% endblock %}